### ISSUE TITLE
In IRsettings.csv column names are in wrong order

### ISSUE THREAD

**Issue by marek05** [ahijazy/PioneerMetastaticAE#3]
I'm getting following error:

> DBMS:
> postgresql
> 
> Error:
> org.postgresql.util.PSQLException: ERROR: syntax error at or near "ADT"
>   Position: 260
> 
> SQL:
> SELECT T.COHORT_DEFINITION_ID as target_id, T.SUBJECT_ID,T.COHORT_START_DATE,T.COHORT_END_DATE,p.YEAR_OF_BIRTH
> FROM user_marek.PioneerMetastaticAE_26092023 T 
> JOIN ohdsi_cdm.person p ON T.subject_id = p.person_id 
> WHERE T.COHORT_DEFINITION_ID=T1_mHSPC ADT only treated 
> 
> R version:
> R version 4.3.1 (2023-06-16)
> 
> Platform:
> aarch64-apple-darwin20
> 
> Attached base packages:
> - stats
> - graphics
> - grDevices
> - datasets
> - utils
> - methods
> - base
> 
> Other attached packages:
> - DatabaseConnector (6.2.0)
> - PioneerMetastaticAE (0.0.1)

Which is caused by this line "WHERE T.COHORT_DEFINITION_ID=T1_mHSPC ADT only treated ". The cohort_definition_id is getting assigned name not id.
The problem seems to with this file (https://github.com/ahijazy/PioneerMetastaticAE/blob/main/inst/settings/IRsettings.csv) where target_id and target_name (and also outcome_id and outcame_name) columns are switched.

**Comment by ahijazy** [comment]
Thanks for reporting this, fixed the variable names
